### PR TITLE
Use non sudo travis

### PR DESCRIPTION
**Pull request by cancan101**
@loli do you want to consider supporting python 2.6 and Python <3.4 ?

### CODE REVIEW

**Comment by loli** [comment]
Without the sudo part, medpy installs without the graphcut extension by default. Hence it passes the build fine, but missed some functionality. The best handing would probably be define two build scenarios. And yes, drop the 2.6 support, by all means!

**Comment by cancan101** [comment]
No rush on this so we want chat once you are back from vacation, but what is needed from sudo in order to get the graphcut extension to work?

**Comment by loli** [comment]
C++ compiler (build-essentials) and libboost with python extension. Maybe also scipy... just the four lines you've removed :)

**Comment by cancan101** [comment]
scipy should be installed as wheel. The other two packages can still be installed in non sudo mode: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

**Comment by cancan101** [comment]
Ok looks like pip was hiding graphcut build issues. I fixed the logging in https://github.com/loli/medpy/pull/63 which will make the build issues obvious.

**Comment by cancan101** [comment]
Ok looks like this is now building for python2.7. Python 3 not working but looking at [new logs for python3 build](https://travis-ci.org/loli/medpy/jobs/302216192) it might be linking against python 2 in the sudo builds:

**Comment by cancan101** [comment]
Ok looks like this is working for python3.4. The boost install only includes:
```
0.01s$ ls /usr/lib/x86_64-linux-gnu/libboost_*
/usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.54.0
/usr/lib/x86_64-linux-gnu/libboost_python.a
/usr/lib/x86_64-linux-gnu/libboost_python-py27.a
/usr/lib/x86_64-linux-gnu/libboost_python-py27.so
/usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0
/usr/lib/x86_64-linux-gnu/libboost_python-py34.a
/usr/lib/x86_64-linux-gnu/libboost_python-py34.so
/usr/lib/x86_64-linux-gnu/libboost_python-py34.so.1.54.0
/usr/lib/x86_64-linux-gnu/libboost_python.so
```

**Comment by cancan101** [comment]
I think this is good to go. It builds graphcut extension on 2.7 and 3.4. I don't think building for 3.5+ worked even on the non sudo build.

**Comment by loli** [comment]
This is beautiful. You know why 3.5+ are unlikely to build?

**Comment by cancan101** [comment]
Doesn't work since the python boost package installed doesn't have support for python 35. Travis is using an old version of Ubuntu

**Pull request merged**
